/**
 * Seed script — uploads all help center articles to Supabase.
 * Run with: npx tsx scripts/seed-help.ts
 *
 * Articles are defined in src/lib/helpContent.ts (static) and
 * also in this file's EXTRA_ARTICLES array (new articles from agents).
 * All are upserted by slug, so it's safe to run multiple times.
 */
import { createClient } from '@supabase/supabase-js'
import { HELP_ARTICLES } from '../src/lib/helpContent'

// ─── Extra articles generated by AI agents ────────────────────────────────────
// PASTE_PART1_HERE
// PASTE_PART2_HERE
// PASTE_PART3_HERE
const EXTRA_ARTICLES: any[] = [
  // Articles will be inserted here after agents complete
]

// ─── Main ────────────────────────────────────────────────────────────────────
async function main() {
  const url  = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key  = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!url || !key) {
    console.error('❌  Missing env vars: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY')
    process.exit(1)
  }

  const supabase = createClient(url, key)

  const allArticles = [
    ...HELP_ARTICLES.map(a => ({
      title:      a.title,
      slug:       a.slug,
      category:   a.category,
      summary:    a.summary,
      body:       a.body,
      tags:       a.tags,
      published:  true,
      sort_order: 0,
    })),
    ...EXTRA_ARTICLES.map(a => ({
      title:      a.title,
      slug:       a.slug,
      category:   a.category,
      summary:    a.summary,
      body:       a.body,
      tags:       a.tags ?? [],
      published:  a.published ?? true,
      sort_order: a.sort_order ?? 0,
    })),
  ]

  // Deduplicate by slug (last one wins)
  const bySlug = new Map<string, any>()
  for (const a of allArticles) bySlug.set(a.slug, a)
  const unique = Array.from(bySlug.values())

  console.log(`📚  Seeding ${unique.length} articles...`)

  // Upsert in batches of 20
  const BATCH = 20
  let inserted = 0
  let errors   = 0

  for (let i = 0; i < unique.length; i += BATCH) {
    const batch = unique.slice(i, i + BATCH)
    const { error } = await supabase
      .from('help_articles')
      .upsert(batch, { onConflict: 'slug' })

    if (error) {
      console.error(`❌  Batch ${Math.floor(i / BATCH) + 1} error:`, error.message)
      errors++
    } else {
      inserted += batch.length
      console.log(`✅  ${inserted}/${unique.length} articles upserted`)
    }
  }

  console.log(`\n🎉  Done! ${inserted} articles seeded, ${errors} batch errors.`)
}

main().catch(err => { console.error(err); process.exit(1) })
